categoryByProducts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:cat_slug>/<slug:slug>/', views.detail, name='detail'),
]

myapp/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Category'


class Products(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField()
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Products'

myapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import *


def home(request):
    category = Category.objects.all()
    return render(request, 'home.html', {"category": category})


def detail(request, cat_slug, slug):
    obj = get_object_or_404(Products, category__slug=cat_slug, slug=slug)
    return render(request, 'detail.html', {'obj': obj})

myapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>category by products </title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    {% block body %}

    {% endblock %}
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
-->
</body>
</html>

myapp/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<h1 class="text-center">Detail page</h1>
<div class="row ">
    <div class="col d-flex justify-content-center">
        <div class="card bg-light text-center" style="width: 50rem;">
            <div class="card-body text-capitalize">
                <h3>{{obj.name}}</h3>
                <p>{{obj.price}}</p>
                <p>{{obj.updated}}</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col">
        <p>Category: </p>
        <p>Tags: </p>
    </div>
</div>


{% endblock %}

myapp/templates/home.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-center">category</h1>
{% for i in category %}
<hr>
<h5 class="text-capitalize text-center">{{i.name}}</h5>
<hr>

<div class="row">
    {% for product in i.products_set.all %}
    <div class="col">
        <div class="card text-dark bg-light" style="width: 18rem;">
            <div class="card-body text-capitalize">
                <a class="card-title" href="{% url 'detail' product.category product.slug %}">{{ product.name }}</a>
                <p>{{ product.price }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endfor %}

{% endblock %}

myapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #80ba86;">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ">
        <li class="nav-item ">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Features</a>
        </li>

      </ul>
    </div>
  </div>
</nav>